# Generated by Django 4.0.4 on 2022-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_error'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='error',
            options={'verbose_name': 'Ошибка', 'verbose_name_plural': 'Ошибки'},
        ),
        migrations.AddField(
            model_name='error',
            name='data',
            field=models.JSONField(default=None),
        ),
    ]
